name: base
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - attrs
  - backcall
  - blas
  - bleach
  - brotlipy
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - cryptography
  - cudatoolkit
  - cycler
  - dbus
  - decorator
  - defusedxml
  - entrypoints
  - expat
  - fontconfig
  - freetype
  - gettext
  - glib
  - gst-plugins-base
  - gstreamer
  - h5py
  - hdf5
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - ipykernel
  - ipython
  - ipython_genutils
  - jedi
  - jinja2
  - joblib
  - jpeg
  - json5
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyterlab
  - jupyterlab_server
  - kiwisolver
  - ld_impl_linux-64
  - libclang
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libiconv
  - libllvm9
  - libpng
  - libsodium
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - llvm-openmp
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - more-itertools
  - nbconvert
  - nbformat
  - ncurses
  - ninja
  - notebook
  - nspr
  - nss
  - numpy
  - numpy-base
  - olefile
  - openmpi
  - openssl
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pluggy
  - prometheus_client
  - prompt-toolkit
  - pthread-stubs
  - ptyprocess
  - py
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyqt
  - pyrsistent
  - pysocks
  - pytest
  - python
  - python-dateutil
  - python_abi
  - pytorch
  - pytorch-cpu
  - pytz
  - pyzmq
  - qt
  - readline
  - requests
  - scikit-learn
  - scipy
  - send2trash
  - setuptools
  - six
  - sqlite
  - terminado
  - testpath
  - tk
  - torchvision
  - tornado
  - traitlets
  - urllib3
  - wcwidth
  - webencodings
  - wheel
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - llvmlite
    - numba
    - pycasso
    - pyqt5-sip
    - pyqtchart
    - pyqtwebengine
    - sdeint
    - sparse
